image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: go-http-hello-world:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} localhost:5000/${CONTAINER_IMAGE}
    - docker push localhost:5000/${CONTAINER_IMAGE}
