apiVersion: v1
kind: Service
metadata:
  name: go-http-hello-world
spec:
  ports:
    - port: 8888
  selector:
    app: go-http-hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-http-hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: go-http-hello-world
    spec:
      containers:
        - name: go
          image: localhost:5000/go-http-hello-world:e1c320ee
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 2
            periodSeconds: 2
